version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
      - $MEMORY_PATH:/home/$USERNAME/memory
      - $DOWNLOADS_PATH:/home/$USERNAME/downloads
      - $ENV_FILE_PATH:/home/$USERNAME/tmp/.env
      - $STARTUP_SCRIPT:/home/$USERNAME/run_in_container.sh
      - $STARTUP_SCRIPT_2:/home/$USERNAME/run_app.sh
    environment:
      - SSH_AUTH_SOCK=/ssh-agent # Use the host's SSH agent within the container
    working_dir: /home/$USERNAME
    command: ["/bin/bash", "/home/$USERNAME/run_in_container.sh"]
    stdin_open: true # Keep STDIN open
    tty: true # Allocate a pseudo-TTY

  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/testBBAAA333
    volumes:
      - $MEMORY_PATH/neo4j/data:/data
      - $MEMORY_PATH/neo4j/logs:/logs
      - $MEMORY_PATH/neo4j/varlib:/var/lib/neo4j/import
      - $MEMORY_PATH/neo4j/plugins:/plugins
    ports:
      - "7474:7474" # Publish HTTP port
      - "7687:7687" # Publish Bolt port
